version: '3.5'

services:
  app:
    build:
      context: ./
      dockerfile: config/dev.Dockerfile
    image: suorituspolut_dev
    volumes:
      - ./:/usr/src/app
      - ./data:/usr/src/app/data
    ports:
      - 8000:8000
    container_name: suorituspolut_dev
