version: 2.1
orbs:
  dockerhub: circleci/docker@0.5.1
workflows:
  test-build-deploy:
    jobs:
      - dockerhub/publish:
          image: suorituspolut/suorituspolut
          extra_build_args: '--build-arg BASE_PATH=/suorituspolut/'
          filters:
            branches:
              only: master