version: 2.1
orbs:
  dockerhub: circleci/docker@0.5.1

jobs:
  test:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - run: bash <(curl -s https://codecov.io/bash)        
workflows:
  test-build-deploy:
    jobs:
      - dockerhub/publish:
          image: suorituspolut/suorituspolut
          tag: 'latest'
          extra_build_args: '--build-arg BASE_PATH=/suorituspolut/'
          filters:
            branches:
              only: master
      - test
        