/* eslint-disable import/prefer-default-export */

export const data = [
  {
    studentId: 1,
    courseCode: 581325,
    courseName: 'Ohjelmoinnin perusteet',
    module: false,
    dayOfCredit: new Date(2013, 1, 10),
    period: 1,
    grade: 5,
  },
  {
    studentId: 1,
    courseCode: 582103,
    courseName: 'Ohjelmoinnin jatkokurssi',
    module: false,
    dayOfCredit: new Date(2014, 1, 1),
    period: 2,
    grade: 4,
  },
  {
    studentId: 1,
    courseCode: 581305,
    courseName: 'Tietokoneen toiminta',
    module: false,
    dayOfCredit: new Date(2014, 1, 1),
    period: 2,
    grade: 4,
  },
  {
    studentId: 1,
    courseCode: 58131,
    courseName: 'Tietorakenteet ja algoritmit',
    module: false,
    dayOfCredit: new Date(2014, 1, 5),
    period: 3,
    grade: 2,
  },
  {
    studentId: 2,
    courseCode: 581325,
    courseName: 'Ohjelmoinnin perusteet',
    module: false,
    dayOfCredit: new Date(2013, 1, 10),
    period: 1,
    grade: 5,
  },
  {
    studentId: 2,
    courseCode: 582103,
    courseName: 'Ohjelmoinnin jatkokurssi',
    module: false,
    dayOfCredit: new Date(2014, 1, 1),
    period: 2,
    grade: 4,
  },
  {
    studentId: 2,
    courseCode: 581305,
    courseName: 'Muut',
    module: false,
    dayOfCredit: new Date(2014, 1, 1),
    period: 2,
    grade: 4,
  },
  {
    studentId: 2,
    courseCode: 58131,
    courseName: 'Tietorakenteet ja algoritmit',
    module: false,
    dayOfCredit: new Date(2014, 1, 5),
    period: 3,
    grade: 2,
  },
  {
    studentId: 3,
    courseCode: 581325,
    courseName: 'Ohjelmoinnin perusteet',
    module: false,
    dayOfCredit: new Date(2014, 1, 10),
    period: 1,
    grade: 5,
  },
  {
    studentId: 3,
    courseCode: 582103,
    courseName: 'Ohjelmoinnin jatkokurssi',
    module: false,
    dayOfCredit: new Date(2014, 1, 1),
    period: 2,
    grade: 4,
  },
  {
    studentId: 3,
    courseCode: 581305,
    courseName: 'Johdatus yliopistomatematiikkaan',
    module: false,
    dayOfCredit: new Date(2014, 1, 1),
    period: 2,
    grade: 4,
  },
  {
    studentId: 3,
    courseCode: 58131,
    courseName: 'Tietorakenteet ja algoritmit',
    module: false,
    dayOfCredit: new Date(2014, 1, 5),
    period: 3,
    grade: 2,
  },
  {
    studentId: 4,
    courseCode: 581325,
    courseName: 'Ohjelmoinnin perusteet',
    module: false,
    dayOfCredit: new Date(2013, 1, 10),
    period: 1,
    grade: 5,
  },
  {
    studentId: 4,
    courseCode: 582103,
    courseName: 'Ohjelmoinnin jatkokurssi',
    module: false,
    dayOfCredit: new Date(2014, 1, 1),
    period: 2,
    grade: 4,
  },
  {
    studentId: 4,
    courseCode: 581305,
    courseName: 'Johdatus yliopistomatematiikkaan',
    module: false,
    dayOfCredit: new Date(2014, 1, 1),
    period: 2,
    grade: 4,
  },
  {
    studentId: 4,
    courseCode: 58131,
    courseName: 'Tietorakenteet ja algoritmit',
    module: false,
    dayOfCredit: new Date(2014, 1, 5),
    period: 3,
    grade: 2,
  },
  {
    studentId: 5,
    courseCode: 581325,
    courseName: 'Ohjelmoinnin perusteet',
    module: false,
    dayOfCredit: new Date(2013, 1, 10),
    period: 1,
    grade: 5,
  },
  {
    studentId: 5,
    courseCode: 582103,
    courseName: 'Ohjelmoinnin jatkokurssi',
    module: false,
    dayOfCredit: new Date(2014, 1, 1),
    period: 2,
    grade: 4,
  },
  {
    studentId: 5,
    courseCode: 581305,
    courseName: 'Tietokoneen toiminta',
    module: false,
    dayOfCredit: new Date(2014, 1, 1),
    period: 2,
    grade: 4,
  },
  {
    studentId: 5,
    courseCode: 58131,
    courseName: 'Tietorakenteet ja algoritmit',
    module: false,
    dayOfCredit: new Date(2014, 1, 5),
    period: 3,
    grade: 2,
  },
  {
    studentId: 6,
    courseCode: 581325,
    courseName: 'Ohjelmoinnin perusteet',
    module: false,
    dayOfCredit: new Date(2013, 1, 10),
    period: 1,
    grade: 5,
  },
  {
    studentId: 6,
    courseCode: 582103,
    courseName: 'Johdatus yliopistomatematiikkaan',
    module: false,
    dayOfCredit: new Date(2014, 1, 1),
    period: 2,
    grade: 4,
  },
  {
    studentId: 6,
    courseCode: 581305,
    courseName: 'Tietokoneen toiminta',
    module: false,
    dayOfCredit: new Date(2014, 1, 1),
    period: 2,
    grade: 4,
  },
  {
    studentId: 6,
    courseCode: 58131,
    courseName: 'Tietorakenteet ja algoritmit',
    module: false,
    dayOfCredit: new Date(2014, 1, 5),
    period: 3,
    grade: 2,
  },
  {
    studentId: 7,
    courseCode: 581325,
    courseName: 'Ohjelmoinnin perusteet',
    module: false,
    dayOfCredit: new Date(2013, 1, 10),
    period: 1,
    grade: 5,
  },
  {
    studentId: 7,
    courseCode: 582103,
    courseName: 'Johdatus yliopistomatematiikkaan',
    module: false,
    dayOfCredit: new Date(2014, 1, 1),
    period: 2,
    grade: 4,
  },
  {
    studentId: 7,
    courseCode: 581305,
    courseName: 'Tietokoneen toiminta',
    module: false,
    dayOfCredit: new Date(2014, 1, 1),
    period: 2,
    grade: 4,
  },
  {
    studentId: 7,
    courseCode: 58131,
    courseName: 'Tietorakenteet ja algoritmit',
    module: false,
    dayOfCredit: new Date(2014, 1, 5),
    period: 3,
    grade: 2,
  },
]